### PR TITLE
🔇 Suppress More CS0168 Warnings

### PR DESCRIPTION
**Pull request by identithree**
This is for the thing @Coca16 did.

### CODE REVIEW

**Comment by asdia0** [comment]
nooooo you're restricting the compilers right to free speech nooooooo

**Comment by identithree** [comment]
Wait no its not, its for something else. Anyways, these warnings are suppressed. I'll fix it when Coca's merge does happen.

**Comment by identithree** [comment]
Can @SpikeViper please please please merge some commits?

**Comment by Coca162** [comment]
my god yes i just want to be able to not have CocaBot have SVAPI attached to it like some pacemaker

**Pull request merged**
