### PR TITLE
Create DOCUMENTATION.md

### PR DESCRIPTION
**Pull request by asdia0**

### CODE REVIEW

**Review by Coca162 — APPROVED** [review]
This is cool and should probably be put in #sv-developer but it would be also nice if this mentioned where these things are in the C# wrapper just for convenience

**Comment by asdia0** [comment]
i could try and make a wrapper version later

**Comment by Coca162** [comment]
> i could try and make a wrapper version later

yeah that would be alright

**Comment by identithree** [comment]
that looks great. I will probably steal something like that for [vexico/spookvooper-api](https://github.com/vexico/spookvooper-api)

**Comment by identithree** [comment]
@asdiapotatisen at this point, why don't you do a wiki?

**Comment by asdia0** [comment]
perms

**Comment by identithree** [comment]
> 
> 
> perms

You can't make it on your repo and then commit it?

**Comment by asdia0** [comment]
i dont think thats how it works chief

**Review by identithree — APPROVED** [review]
Good overall, the warnings in Group.cs and Transaction.cs are fixed in my PR.

**Comment by identithree** [comment]
> i dont think thats how it works chief

[It does actually exist](https://gist.github.com/larrybotha/10650410), however that would involve Spike typing stuff into a CLI so I can safely assume that it wouldn't happen.

**Comment by SpikeViper** [comment]
Wow, what a rude child. I literally run several servers which only have a CLI, you egg.

**Pull request merged**
